name: Selenium tests

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on
        default: http://localhost:4444
      browser:
        description: 'Select browsers for testing'
        required: true
        type: choice
        options:
          - "chrome"
          - "firefox"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Start the Selenium Server
        if: ${{ !contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run -d --shm-size="2g" --port 4444 selenium/standalone-${{ github.event.inputs.browser }}

      - name: Run Tests
        env:
          BROWSER: ${{ github.event.inputs.browser }}
          GRID_URL: ${{ github.event.inputs.grid_url }}
        run: |
          mvn -q test